name: GitHub Actions AI
run-name: test-runner-gabri

on:
  schedule:
    - cron: '0 */2 * * *' 
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  call-workflow:
    uses: org-test-reply-1/platform-ai-workflows/.github/workflows/ai-failure-handler.yml@main
    secrets: inherit
