name: GitHub Actions AI
run-name: test-runner-gabri

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: org-test-reply-1/platform-ai-workflows/.github/workflows/ai-failure-handler.yml@main
    secrets: inherit
