name: App Pipeline

on:
  workflow_dispatch:

jobs:
  # ── 1. Build & Test ────────────────────────────────────────────────────────
  build:
    name: .NET Build & Test
    uses: org-test-reply-1/platform-workflows/.github/workflows/ci-dotnet.yml@main
    with:
      dotnet-version: "9.0.x"
      project-path: "."
      run-tests: true

  # ── 2. Docker        ───────────────────────────────────
  docker:
    name: Docker Build & Push
    needs: build
    if: github.event_name == 'push'
    uses: org-test-reply-1/platform-workflows/.github/workflows/docker-build-push.yml@main
    with:
      image-name: ${{ github.repository_owner }}/dotnetapp
      registry: ghcr.io
      dockerfile: ./Dockerfile
      context: .
      dry-run: true
