name: arc-runner-stress-test

on:
  workflow_dispatch:

jobs:
  dotnet_load:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        worker: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

    runs-on: arc-runner-dotnet

    steps:
      - name: CPU stress (.NET runner)
        run: |
          echo "Runner $(hostname)"
          timeout 300s bash -c '
            while true; do
              sha256sum /dev/zero
            done
          ' || [ $? -eq 124 ]

  react_load:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        worker: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

    runs-on: arc-runner-react

    steps:
      - name: CPU stress (React runner)
        run: |
          echo "Runner $(hostname)"
          timeout 300s bash -c '
            while true; do
              sha256sum /dev/zero
            done
          ' || [ $? -eq 124 ]
